package Vista;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

public class JF_Invitado extends javax.swing.JFrame {

    public JF_Invitado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Panel = new javax.swing.JPanel();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_Nombre = new javax.swing.JLabel();
        lbl_Apellido = new javax.swing.JLabel();
        lbl_Dni = new javax.swing.JLabel();
        lbl_MenVeg = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        checkBox_MenVeg = new javax.swing.JCheckBox();
        btn_Agregar = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_VerTodos = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_GuardarCambios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_Titulo.setText("Lista de Invitados");

        lbl_Nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Nombre.setText("Nombre:");

        lbl_Apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Apellido.setText("Apellido:");

        lbl_Dni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_Dni.setText("DNI:");

        lbl_MenVeg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MenVeg.setText("Menú Vegano?");

        checkBox_MenVeg.setText("Sí");

        btn_Agregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Agregar.setText("Agregar");

        btn_Editar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Editar.setText("Editar");

        btn_Borrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Borrar.setText("Borrar");

        btn_VerTodos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_VerTodos.setText("Ver todos");

        btn_Limpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Limpiar.setText("Limpiar");

        btn_Buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Buscar.setText("Buscar");

        btn_GuardarCambios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_GuardarCambios.setText("Guardar cambios");

        javax.swing.GroupLayout jP_PanelLayout = new javax.swing.GroupLayout(jP_Panel);
        jP_Panel.setLayout(jP_PanelLayout);
        jP_PanelLayout.setHorizontalGroup(
            jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_PanelLayout.createSequentialGroup()
                        .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jP_PanelLayout.createSequentialGroup()
                                .addComponent(lbl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Nombre))
                            .addGroup(jP_PanelLayout.createSequentialGroup()
                                .addComponent(lbl_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Apellido))
                            .addGroup(jP_PanelLayout.createSequentialGroup()
                                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_MenVeg))
                                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jP_PanelLayout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(txt_DNI))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkBox_MenVeg)
                                        .addGap(34, 34, 34))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PanelLayout.createSequentialGroup()
                                .addComponent(btn_Agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_GuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
            .addGroup(jP_PanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btn_VerTodos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jP_PanelLayout.setVerticalGroup(
            jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_PanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MenVeg)
                    .addComponent(checkBox_MenVeg))
                .addGap(18, 18, 18)
                .addComponent(btn_Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btn_Editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_GuardarCambios)
                .addGap(18, 18, 18)
                .addGroup(jP_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar)
                    .addComponent(btn_Borrar))
                .addGap(18, 18, 18)
                .addComponent(btn_VerTodos)
                .addGap(53, 53, 53))
        );

        jT_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "DNI", "Menú Vegano"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jT_Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jP_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jP_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JF_Invitado().setVisible(true);
                
            }
        });
    }

    public JButton getBtn_Agregar() {
        return btn_Agregar;
    }

    public void setBtn_Agregar(JButton btn_Agregar) {
        this.btn_Agregar = btn_Agregar;
    }

    public JButton getBtn_Borrar() {
        return btn_Borrar;
    }

    public void setBtn_Borrar(JButton btn_Borrar) {
        this.btn_Borrar = btn_Borrar;
    }

    public JButton getBtn_Editar() {
        return btn_Editar;
    }

    public void setBtn_Editar(JButton btn_Editar) {
        this.btn_Editar = btn_Editar;
    }

    public JButton getBtn_VerTodos() {
        return btn_VerTodos;
    }

    public void setBtn_VerTodos(JButton btn_VerTodos) {
        this.btn_VerTodos = btn_VerTodos;
    }

    public JCheckBox getCheckBox_MenVeg() {
        return checkBox_MenVeg;
    }

    public void setCheckBox_MenVeg(JCheckBox checkBox_MenVeg) {
        this.checkBox_MenVeg = checkBox_MenVeg;
    }

    public JPanel getjP_Panel() {
        return jP_Panel;
    }

    public void setjP_Panel(JPanel jP_Panel) {
        this.jP_Panel = jP_Panel;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjT_Tabla() {
        return jT_Tabla;
    }

    public void setjT_Tabla(JTable jT_Tabla) {
        this.jT_Tabla = jT_Tabla;
    }

    public JLabel getLbl_Apellido() {
        return lbl_Apellido;
    }

    public void setLbl_Apellido(JLabel lbl_Apellido) {
        this.lbl_Apellido = lbl_Apellido;
    }

    public JLabel getLbl_Dni() {
        return lbl_Dni;
    }

    public void setLbl_Dni(JLabel lbl_Dni) {
        this.lbl_Dni = lbl_Dni;
    }

    public JLabel getLbl_MenVeg() {
        return lbl_MenVeg;
    }

    public void setLbl_MenVeg(JLabel lbl_MenVeg) {
        this.lbl_MenVeg = lbl_MenVeg;
    }

    public JLabel getLbl_Nombre() {
        return lbl_Nombre;
    }

    public void setLbl_Nombre(JLabel lbl_Nombre) {
        this.lbl_Nombre = lbl_Nombre;
    }

    public JLabel getLbl_Titulo() {
        return lbl_Titulo;
    }

    public void setLbl_Titulo(JLabel lbl_Titulo) {
        this.lbl_Titulo = lbl_Titulo;
    }

    public JTextField getTxt_Apellido() {
        return txt_Apellido;
    }

    public void setTxt_Apellido(JTextField txt_Apellido) {
        this.txt_Apellido = txt_Apellido;
    }

    public JTextField getTxt_DNI() {
        return txt_DNI;
    }

    public void setTxt_DNI(JTextField txt_DNI) {
        this.txt_DNI = txt_DNI;
    }

    public JTextField getTxt_Nombre() {
        return txt_Nombre;
    }

    public void setTxt_Nombre(JTextField txt_Nombre) {
        this.txt_Nombre = txt_Nombre;
    }

    public JButton getBtn_Limpiar() {
        return btn_Limpiar;
    }

    public void setBtn_Limpiar(JButton btn_Limpiar) {
        this.btn_Limpiar = btn_Limpiar;
    }

    public JButton getBtn_Buscar() {
        return btn_Buscar;
    }

    public void setBtn_Buscar(JButton btn_Buscar) {
        this.btn_Buscar = btn_Buscar;
    }

    public JButton getBtn_GuardarCambios() {
        return btn_GuardarCambios;
    }

    public void setBtn_GuardarCambios(JButton btn_GuardarCambios) {
        this.btn_GuardarCambios = btn_GuardarCambios;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_GuardarCambios;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_VerTodos;
    public javax.swing.JCheckBox checkBox_MenVeg;
    private javax.swing.JPanel jP_Panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jT_Tabla;
    private javax.swing.JLabel lbl_Apellido;
    private javax.swing.JLabel lbl_Dni;
    private javax.swing.JLabel lbl_MenVeg;
    private javax.swing.JLabel lbl_Nombre;
    private javax.swing.JLabel lbl_Titulo;
    public javax.swing.JTextField txt_Apellido;
    public javax.swing.JTextField txt_DNI;
    public javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
